# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5abe4fbfd921e7f06b491df1105a554b6544f8e6787d62d43d1dff8bea761de6ebe94e6d828d5a4e9dbf044c60b0f09b661d4dd9834abf12d523aa3b2b9a36eb

test:
  secret_key_base: dadeda1e72046d7f512412dead39b5d546baf8674867b1d7e9d6f58c8705983964da42f1bc20dd316173c1aa220f0f7d6d5194ca200d9aad8e73ae1a204d162f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
